name: Enable Developer Command Prompt
description: Configure Microsoft Visual C++ command line
inputs:
  arch:
    description: Target architecture
    default: x64
  sdk:
    description: Windows SDK number to build for
  spectre:
    description: Enable Specre mitigations
  toolset:
    description: VC++ compiler toolset version
  uwp:
    description: Build for Universal Windows Platform
runs:
  using: node12
  main: index.js
branding:
  icon: terminal
  color: bule
