name: Build-CPP-Action

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    name: buildproject
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Download Dependencies
        run: npm install
      - name: SetUp CL Environment 
        uses: ./
      - name: Compile & Run Test Cases
        shell: cmd
        run: |
          cl.exe TestFrameWork\TestMain.cpp TestFrameWork\MyTestCases.cpp
          TestMain.exe
  audit:
    name: npm audit
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - run: npm install
      - run: npm audit --audit-level=moderate
